In [1]:
from skimage import io, color
rgb = io.imread('1-1-s-150_real.png')
lab = color.rgb2lab(rgb)

In [2]:
print(rgb)

[[[238 175 153]
  [237 175 153]
  [238 177 155]
  ...
  [233 175 150]
  [233 175 150]
  [235 177 151]]

 [[238 176 154]
  [238 175 154]
  [237 174 155]
  ...
  [232 175 151]
  [232 174 151]
  [233 173 150]]

 [[238 176 157]
  [240 178 159]
  [237 175 156]
  ...
  [233 174 154]
  [232 172 152]
  [233 173 153]]

 ...

 [[226 202 177]
  [225 200 176]
  [224 199 176]
  ...
  [220 194 174]
  [220 194 174]
  [219 194 171]]

 [[222 197 175]
  [222 196 174]
  [223 197 175]
  ...
  [219 192 172]
  [222 195 175]
  [221 195 173]]

 [[223 198 177]
  [223 197 175]
  [223 197 175]
  ...
  [224 196 176]
  [224 197 177]
  [218 192 170]]]


In [3]:
print(lab)

[[[76.76395537 20.17057541 20.33252386]
  [76.65943171 19.78727379 20.1720399 ]
  [77.27562165 19.34890502 19.95947766]
  ...
  [76.18494856 17.8895508  21.07242842]
  [76.18494856 17.8895508  21.07242842]
  [76.8869154  17.71658096 21.53002028]]

 [[77.01954005 19.75930082 20.1453389 ]
  [76.78400802 20.29011918 19.82039227]
  [76.46437542 20.55977514 18.82176428]
  ...
  [76.10188505 17.62439288 20.40218205]
  [75.86339533 18.15728355 20.07369356]
  [75.70937227 18.95475625 20.4186204 ]]

 [[77.080344   20.12282042 18.61024005]
  [77.79971402 20.06842355 18.56048175]
  [76.72020361 20.1502891  18.63539328]
  ...
  [76.02745883 18.90794602 18.69359046]
  [75.40835485 19.34534898 18.90403227]
  [75.76986901 19.31801335 18.87844645]]

 ...

 [[82.69266449  4.51668964 15.56426166]
  [82.08346482  5.04930085 15.22738178]
  [81.7459128   5.20277646 14.74011032]
  ...
  [80.09899518  6.05756565 13.43715775]
  [80.09899518  6.05756565 13.43715775]
  [79.94590432  5.24552366 14.81488942]]

 [

In [7]:
#lab 변환
rgb1 = color.lab2rgb(lab)*256
print(rgb1.astype(int))

[[[238 175 153]
  [237 175 153]
  [238 177 155]
  ...
  [233 175 150]
  [233 175 150]
  [235 177 151]]

 [[238 176 154]
  [238 175 154]
  [237 174 155]
  ...
  [232 175 151]
  [232 174 151]
  [233 173 150]]

 [[238 176 157]
  [240 178 159]
  [237 175 156]
  ...
  [233 174 154]
  [232 172 152]
  [233 173 153]]

 ...

 [[226 202 177]
  [225 200 176]
  [224 199 176]
  ...
  [220 194 174]
  [220 194 174]
  [219 194 171]]

 [[222 197 175]
  [222 196 174]
  [223 197 175]
  ...
  [219 192 172]
  [222 195 175]
  [221 195 173]]

 [[223 198 177]
  [223 197 175]
  [223 197 175]
  ...
  [224 196 176]
  [224 197 177]
  [218 192 170]]]


In [15]:
#lab 변환
lab1 = io.imread('Lab.png')
rgb1 = color.lab2rgb(lab)*256
print(lab1)

[[[203  60  44]
  [203  60  44]
  [202  61  44]
  ...
  [209  48  45]
  [205  47  48]
  [202  48  48]]

 [[200  62  43]
  [202  61  43]
  [203  61  42]
  ...
  [208  49  42]
  [204  50  45]
  [205  49  46]]

 [[200  63  43]
  [200  62  43]
  [200  61  43]
  ...
  [207  48  44]
  [202  49  46]
  [203  48  47]]

 ...

 [[226  13  28]
  [225   9  28]
  [224   9  28]
  ...
  [223  11  26]
  [223  11  26]
  [226  11  25]]

 [[223  13  28]
  [226  10  28]
  [225   9  28]
  ...
  [224  11  26]
  [223  11  26]
  [225  11  26]]

 [[226  12  28]
  [225   9  28]
  [222   9  28]
  ...
  [221  11  26]
  [222  11  26]
  [221  11  26]]]


In [16]:
from scipy.misc import imsave
print(rgb1.astype(int))
imsave('filename.png', rgb1) 

[[[242 164 147]
  [242 165 147]
  [241 163 146]
  ...
  [242 174 152]
  [238 170 146]
  [235 167 143]]

 [[240 162 145]
  [241 163 146]
  [242 164 148]
  ...
  [241 172 152]
  [238 168 147]
  [239 169 148]]

 [[241 161 145]
  [240 162 145]
  [239 161 145]
  ...
  [240 172 150]
  [235 167 145]
  [236 167 144]]

 ...

 [[235 199 178]
  [232 199 177]
  [231 198 176]
  ...
  [230 196 177]
  [231 197 177]
  [233 200 180]]

 [[232 196 175]
  [233 200 178]
  [232 199 177]
  ...
  [232 198 178]
  [231 197 177]
  [232 198 179]]

 [[235 199 178]
  [232 199 178]
  [229 196 174]
  ...
  [229 195 175]
  [229 195 176]
  [228 194 175]]]


C:\Users\Meereh Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
print(type(rgb1))

<class 'numpy.ndarray'>


In [23]:
output = color.lab2rgb(lab)*256

In [24]:
print(output)

[[[111.43529412 108.42352941 125.49019608]
  [111.43529412 108.42352941 125.49019608]
  [111.43529412 110.43137255 126.49411765]
  ...
  [112.43921569 110.43137255 123.48235294]
  [113.44313725 111.43529412 124.48627451]
  [113.44313725 111.43529412 124.48627451]]

 [[111.43529412 108.42352941 125.49019608]
  [111.43529412 108.42352941 125.49019608]
  [110.43137255 109.42745098 125.49019608]
  ...
  [112.43921569 110.43137255 123.48235294]
  [112.43921569 110.43137255 123.48235294]
  [112.43921569 110.43137255 123.48235294]]

 [[112.43921569 109.42745098 126.49411765]
  [111.43529412 108.42352941 125.49019608]
  [109.42745098 108.42352941 124.48627451]
  ...
  [111.43529412 111.43529412 123.48235294]
  [111.43529412 111.43529412 123.48235294]
  [110.43137255 110.43137255 122.47843137]]

 ...

 [[  9.03529412   5.01960784   6.02352941]
  [ 10.03921569   6.02352941   7.02745098]
  [  8.03137255   6.02352941   7.02745098]
  ...
  [  6.02352941   4.01568627   5.01960784]
  [  6.02352941   

In [21]:
rgb1=color.xyz2rgb(output)*256


In [22]:
print(rgb1)

[[[111.43529412 108.42352941 125.49019608]
  [111.43529412 108.42352941 125.49019608]
  [111.43529412 110.43137255 126.49411765]
  ...
  [112.43921569 110.43137255 123.48235294]
  [113.44313725 111.43529412 124.48627451]
  [113.44313725 111.43529412 124.48627451]]

 [[111.43529412 108.42352941 125.49019608]
  [111.43529412 108.42352941 125.49019608]
  [110.43137255 109.42745098 125.49019608]
  ...
  [112.43921569 110.43137255 123.48235294]
  [112.43921569 110.43137255 123.48235294]
  [112.43921569 110.43137255 123.48235294]]

 [[112.43921569 109.42745098 126.49411765]
  [111.43529412 108.42352941 125.49019608]
  [109.42745098 108.42352941 124.48627451]
  ...
  [111.43529412 111.43529412 123.48235294]
  [111.43529412 111.43529412 123.48235294]
  [110.43137255 110.43137255 122.47843137]]

 ...

 [[  9.03529412   5.01960784   6.02352941]
  [ 10.03921569   6.02352941   7.02745098]
  [  8.03137255   6.02352941   7.02745098]
  ...
  [  6.02352941   4.01568627   5.01960784]
  [  6.02352941   

In [8]:
v = io.imread('10-3-s-1000_real.png')
print(v)

[[[229 168 148]
  [228 168 148]
  [230 169 149]
  ...
  [225 149 139]
  [226 149 139]
  [226 148 139]]

 [[232 172 152]
  [231 170 150]
  [229 169 149]
  ...
  [223 149 139]
  [226 149 139]
  [226 149 139]]

 [[229 169 149]
  [228 168 147]
  [230 169 149]
  ...
  [222 148 137]
  [225 147 138]
  [225 147 138]]

 ...

 [[224 205 201]
  [225 206 202]
  [223 204 200]
  ...
  [213 197 192]
  [210 194 189]
  [212 195 190]]

 [[225 206 202]
  [222 203 199]
  [225 206 202]
  ...
  [211 195 190]
  [213 197 192]
  [213 196 191]]

 [[224 205 203]
  [223 204 201]
  [225 205 203]
  ...
  [209 194 188]
  [213 197 191]
  [212 195 190]]]


In [9]:
r = color.rgb2lab(v)
print(r)

[[[74.06452842 19.8419653  19.17025927]
  [73.9591553  19.45658827 19.00830387]
  [74.42706232 19.8134289  19.14355792]
  ...
  [69.01834359 27.41032118 17.06444795]
  [69.13425975 27.79244226 17.24290444]
  [68.90748113 28.32626228 16.92859073]]

 [[75.40835485 19.34534898 18.90403227]
  [74.78928144 19.7850881  19.11705722]
  [74.32192928 19.42848976 18.98194177]
  ...
  [68.78760186 26.64505019 16.70906151]
  [69.13425975 27.79244226 17.24290444]
  [69.13425975 27.79244226 17.24290444]]

 [[74.32192928 19.42848976 18.98194177]
  [73.93888522 19.33552495 19.5243719 ]
  [74.42706232 19.8134289  19.14355792]
  ...
  [68.40123586 26.5645924  17.26616641]
  [68.54311948 28.36365833 16.96089912]
  [68.54311948 28.36365833 16.96089912]]

 ...

 [[83.82396216  5.9346648   4.38566319]
  [84.18162445  5.92862639  4.38123454]
  [83.46598216  5.9407392   4.39011862]
  ...
  [80.67496021  4.74606234  4.52759978]
  [79.59114775  4.7615777   4.54162318]
  [80.03644106  5.11443025  4.66845884]]

 [